### PR TITLE
added The Pokémon notebook

### LINKED ISSUE #93: Make notebook Pokémon types
Add a notebook simulating Pokemon battles based on [this](https://www.moll.dev/projects/effective-multi-dispatch/?s=03) blog post.

### PR DESCRIPTION
**Pull request by wardvanbelle**
added the completed Pokémon notebook. This notebook is an example of composite types and how to easily expand function with them. This notebook should be moved from the notebooks map to the example map if it's okay.
It also resolves #93

### CODE REVIEW

**Comment by MichielStock** [comment]
Fixed dual types! You might overload `Base.show` to show the types correctly

**Comment by wardvanbelle** [comment]
Found a small spelling mistake. What do you mean by showing types correctly? Do you mean something like Dualtype(Grass, Poisson) instead of Dualtype(Grass(), Poisson())?

**Comment by MichielStock** [comment]
Overload show such that a type is printed correctly (and works for Dual types such that you can see the types they compose from). This way you don't have to perform string processing in `attack!`.

**Comment by wardvanbelle** [comment]
Normally it should work now.

**Comment by MichielStock** [comment]
Fixed some issues with the type. Now it's fine

**Pull request merged**
