### PR TITLE
Type system (day 2)

### PR DESCRIPTION
**Pull request by MichielStock**
Starting day two:
- [x] outline type system (primitive and abstract)
   - [x] add Questions
- [x] composite types
  - [x] Transform to Pluto
- [ ] dispatch

### CODE REVIEW

**Comment by Beramos** [comment]
A part of the primitives is already included in day1: #37 [https://github.com/Beramos/DS-Julia2925/pull/37/commits/9ae6897380057159849c8b54a994f365a0882905](commit).

**Comment by MichielStock** [comment]
I thought the plan was to assimilate this notebook into day 2

**Comment by Beramos** [comment]
Well the plan was to give a minor introduction into types and MD on day 1
so that's what I included. The rest of the type system remains for day 2.
If you check the commit you will see I only included a small part of
Julia925. But if you have a better idea for the introduction into types in
day1 ( with the purposes of explaining MD) shoot!

Op ma 4 jan. 2021 16:44 schreef Michiel Stock <notifications@github.com>:

**Comment by MichielStock** [comment]
Don't use the notebook from types for day 1. The type system is covered on day 2. **Mention** the notion of type and dispatch at some points in day 1 to make people familiar with it.

**Comment by Beramos** [comment]
Ok

**Comment by MichielStock** [comment]
Ok, now scripts transformed into notebooks. These can be tidied up now.

**Comment by Beramos** [comment]
@MichielStock  I'll assign myself to this

**Comment by Beramos** [comment]
@MichielStock  should I also review flatland here? There seems to be no explanation whatsoever

**Comment by MichielStock** [comment]
🚧

And moved to the project2 branch

**Pull request merged**
