### PR TITLE
03 exercises reworked

### LINKED ISSUE #85: [03-exercises] Crash when using Images
I have been exploring this bug a little. Hangs on a certain cell in this notebook. After a few minutes the following or a similiar error trace is thrown 

```
No Changes to `~/Desktop/DS-Julia2925/notebooks/Manifest.toml`
┌ Info: 
│ 
│     Welcome to Pluto v0.12.18 🎈
│     Start a notebook server using:
│ 
│   julia> Pluto.run()
│ 
│     Have a look at the FAQ:
│     https://github.com/fonsp/Pluto.jl/wiki
└ 

Opening http://localhost:1234/?secret=SP8gUjzk in your default browser... ~ have fun!

Press Ctrl+C in this terminal to stop Pluto


(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34bf739290' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34be7fe920' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34be14f100' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34c0043bf0' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34c7fdc150' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34c62b5970' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34b2ad4ec0' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34c7fdcbf0' of type 'MaiAtkType1'
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: default value of option force_s3tc_enable overridden by environment.

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34b1c57dd0' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34b376ed30' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34a8b226a0' of type 'MaiAtkType1'

(firefox:14100): GLib-GObject-WARNING **: /build/glib2.0-xkQkqE/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7f34b4a577e0' of type 'MaiAtkType1'
      From worker 6:	    Fetching: [>                                        ]
      From worker 6:	signal (11): Segmentation fault
      From worker 6:	in expression starting at none:1
      From worker 6:	jl_object_id_ at /buildworker/worker/package_linux64/build/src/builtins.c:349
      From worker 6:	type_hash at /buildworker/worker/package_linux64/build/src/jltypes.c:1002
      From worker 6:	typekey_hash at /buildworker/worker/package_linux64/build/src/jltypes.c:1014 [inlined]
      From worker 6:	jl_precompute_memoized_dt at /buildworker/worker/package_linux64/build/src/jltypes.c:1048
      From worker 6:	inst_datatype_inner at /buildworker/worker/package_linux64/build/src/jltypes.c:1314
      From worker 6:	jl_apply_tuple_type_v_ at /buildworker/worker/package_linux64/build/src/jltypes.c:1385 [inlined]
      From worker 6:	jl_apply_tuple_type_v at /buildworker/worker/package_linux64/build/src/jltypes.c:1395
      From worker 6:	arg_type_tuple at /buildworker/worker/package_linux64/build/src/gf.c:1851
      From worker 6:	jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2361 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2394
      From worker 6:	_writecallback at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:422
      From worker 6:	unknown function (ip: 0x7feb156bdb71)
      From worker 6:	png_write_data at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_chunk_header at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_complete_chunk at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_compress_IDAT at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_finish_row at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_filtered_row at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_find_filter at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_row at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	png_write_image at /home/bram/.julia/artifacts/b0cf018645acb4148a4234c116eb74799ef63fc1/lib/libpng16.so (unknown line)
      From worker 6:	_write_image at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:426 [inlined]
      From worker 6:	#_save#15 at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:414
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	_save##kw at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:344
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	#13 at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:326
      From worker 6:	maybe_lock at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:36 [inlined]
      From worker 6:	maybe_lock at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:38 [inlined]
      From worker 6:	#save#12 at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:323
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	save at /home/bram/.julia/packages/PNGFiles/CQUsD/src/io.jl:315
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
      From worker 6:	jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:705
      From worker 6:	#invokelatest#1 at ./essentials.jl:710
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
      From worker 6:	invokelatest at ./essentials.jl:709
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
      From worker 6:	#save#7 at /home/bram/.julia/packages/ImageIO/uPn5K/src/ImageIO.jl:46
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	save##kw at /home/bram/.julia/packages/ImageIO/uPn5K/src/ImageIO.jl:41
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	inner at ./essentials.jl:713
      From worker 6:	unknown function (ip: 0x7feb156d86dc)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
      From worker 6:	jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:705
      From worker 6:	#invokelatest#1 at ./essentials.jl:714 [inlined]
      From worker 6:	invokelatest##kw at ./essentials.jl:709 [inlined]
      From worker 6:	#save#33 at /home/bram/.julia/packages/FileIO/TyKdX/src/loadsave.jl:233
      From worker 6:	save##kw at /home/bram/.julia/packages/FileIO/TyKdX/src/loadsave.jl:217
      From worker 6:	unknown function (ip: 0x7feb156d85c6)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	#show#13 at /home/bram/.julia/packages/ImageShow/9kpaq/src/showmime.jl:43
      From worker 6:	unknown function (ip: 0x7feb156d6e6b)
      From worker 6:	show at /home/bram/.julia/packages/ImageShow/9kpaq/src/showmime.jl:28
      From worker 6:	unknown function (ip: 0x7feb156d4e05)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	show_richest at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:601
      From worker 6:	unknown function (ip: 0x7feb15681da5)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	#sprint_withreturned#28 at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:549
      From worker 6:	sprint_withreturned##kw at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:548
      From worker 6:	unknown function (ip: 0x7feb156d4aec)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	format_output_default at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:474
      From worker 6:	#format_output#17 at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:491 [inlined]
      From worker 6:	format_output##kw at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:491
      From worker 6:	unknown function (ip: 0x7feb156d47b5)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	formatted_result_of at /home/bram/.julia/packages/Pluto/luIaC/src/runner/PlutoRunner.jl:416
      From worker 6:	unknown function (ip: 0x7feb1566ceb8)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
      From worker 6:	eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
      From worker 6:	eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
      From worker 6:	eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
      From worker 6:	jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
      From worker 6:	jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
      From worker 6:	jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:883
      From worker 6:	eval at ./boot.jl:331
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
      From worker 6:	#106 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:294
      From worker 6:	run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:79
      From worker 6:	macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:294 [inlined]
      From worker 6:	#105 at ./task.jl:356
      From worker 6:	unknown function (ip: 0x7feb1560e92c)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
      From worker 6:	start_task at /buildworker/worker/package_linux64/build/src/task.c:705
      From worker 6:	unknown function (ip: (nil))
      From worker 6:	Allocations: 59321767 (Pool: 59308398; Big: 13369); GC: 60
Worker 6 terminated.Distributed.ProcessExitedException(6)

Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled)) at ./task.jl:656
 [2] wait at ./task.jl:713 [inlined]
 [3] wait(::Base.GenericCondition{ReentrantLock}) at ./condition.jl:106
 [4] take_buffered(::Channel{Any}) at ./channels.jl:387
 [5] take!(::Channel{Any}) at ./channels.jl:381
 [6] take!(::Distributed.RemoteValue) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:599
 [7] remotecall_fetch(::Function, ::Distributed.Worker, ::Module, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:390
 [8] remotecall_fetch(::Function, ::Distributed.Worker, ::Module, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:386
 [9] #remotecall_fetch#146 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421 [inlined]
 [10] remotecall_fetch at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421 [inlined]
 [11] remotecall_eval at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/macros.jl:241 [inlined]
 [12] (::Pluto.WorkspaceManager.var"#12#13"{Base.UUID,Bool,Nothing,Pluto.WorkspaceManager.Workspace})() at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/WorkspaceManager.jl:260
 [13] withtoken(::Pluto.WorkspaceManager.var"#12#13"{Base.UUID,Bool,Nothing,Pluto.WorkspaceManager.Workspace}, ::Pluto.Token) at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/Tokens.jl:18
 [14] format_fetch_in_workspace at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/WorkspaceManager.jl:259 [inlined]
 [15] format_fetch_in_workspace at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/WorkspaceManager.jl:256 [inlined]
 [16] eval_format_fetch_in_workspace(::Tuple{Pluto.ServerSession,Pluto.Notebook}, ::Expr, ::Base.UUID, ::Bool, ::Tuple{Set{Symbol},Set{Symbol}}) at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/WorkspaceManager.jl:244
 [17] run_single!(::Tuple{Pluto.ServerSession,Pluto.Notebook}, ::Pluto.Cell, ::Pluto.ReactiveNode) at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/Run.jl:107
 [18] run_reactive!(::Pluto.ServerSession, ::Pluto.Notebook, ::Pluto.NotebookTopology, ::Pluto.NotebookTopology, ::Array{Pluto.Cell,1}; deletion_hook::Function, persist_js_state::Bool) at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/Run.jl:78
 [19] run_reactive! at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/Run.jl:26 [inlined]
 [20] macro expansion at /home/bram/.julia/packages/Pluto/luIaC/src/evaluation/Run.jl:13 [inlined]
 [21] (::Pluto.var"#79#81"{Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Pluto.ServerSession,Pluto.Notebook,Pluto.NotebookTopology,Pluto.NotebookTopology,Array{Pluto.Cell,1}})() at ./task.jl:356
```

My setup is `julia1.5.3` using `4.13.0-32-generic GNU/Linux
`

For me this occurs here 

```julia
Gray.(mini_image)
```

I have the feeling that for some other people this occurs here
```julia
mini_image = [RGB(0.8, 0.6, 0.1) RGB(0.2, 0.8, 0.9) RGB(0.8, 0.6, 0.1);
				RGB(0.2, 0.8, 0.9) RGB(0.8, 0.2, 0.2) RGB(0.2, 0.8, 0.9);
				RGB(0.8, 0.6, 0.1) RGB(0.2, 0.8, 0.9) RGB(0.8, 0.6, 0.1)]
```

If we do not discover how to fix this, It might be better to just not create custom images as an array of colors but it still seems weird that such a basic operation leads to so many problems

### PR DESCRIPTION
**Pull request by wardvanbelle**
The adjustments in the 03-extra_exercises notebook resolve the following issues:
* resolves #85
* adds extra explanation to some questions
* removes the answer verification where necessary
* removes some spelling mistakes

### CODE REVIEW

**Comment by MichielStock** [comment]
A lot of errors here, likely because DSJulia is not installed. Will likely be fixed when the launch issue is resolved.

**Comment by MichielStock** [comment]
I think that:
- notebooks/day1/COVID19BE_CASES_AGESEX.csv
- pretty_bird.jpeg
will be downloaded automatically. They can be deleted from the repo.

**Review by MichielStock — CHANGES_REQUESTED** [review]
delete data files

**Comment by MichielStock** [comment]
You can remove the `/spectra/` folder

**Comment by wardvanbelle** [comment]
I deleted the Spectra folder and added the Solutions and fixed the DSJulia problem here.

**Review by Beramos — APPROVED** [review]
All seems to work fine!. Precompilation time reduced significantly for the Pluto 12 & Pluto 15

**Comment by Beramos** [comment]
@MichielStock  AFAIK this is OK and can be merged

**Comment by MichielStock** [comment]
So just run the `launch.jl`?

**Comment by Beramos** [comment]
Seems to work for me on a clean Julia install 1.6

Op di 7 sep. 2021 17:53 schreef Michiel Stock ***@***.***>:

**Pull request merged**
